name: message
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    env_file: ./config/server.env
    ports:
      - ${SERVER_PORT:-8080}:8080
    depends_on:
      - postgres
      - kafka
    restart: on-failure

  postgres:
    image: postgres:15.7-alpine3.20
    container_name: postgres
    env_file: ./config/postgres.env
    volumes:
      - ./internal/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/postgres:/var/lib/postgresql/data:rw


  kafka:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka
    env_file: ./config/kafka.env
    volumes:
        - ./data/kafka:/var/lib/kafka/data
    user: 0:0