name: message
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    ports:
      - ${SERVER_PORT}:8080
    depends_on:
      - postgres
      - kafka
    restart: on-failure

  postgres:
    image: postgres:15.7-alpine3.20
    env_file: .env
    container_name: postgres

    volumes:
      - ./internal/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./internal/postgres/db:/var/lib/postgresql/data:rw
    # TODO удалить положив на сервер
    user:
      ${USER_GROUP}


  kafka:
    image: confluentinc/cp-kafka:7.7.0
    env_file: .env
    container_name: kafka

    volumes:
        - ./data/kafka:/var/lib/kafka/data
    user:
      0:0
